# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-07 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_str', models.CharField(max_length=200)),
                ('votes_int', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_str', models.CharField(max_length=200)),
                ('publish_date', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
